apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra1
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters: {}
  template:
    metadata:
      name: "{{ .name }}-infra1"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
      annotations:
        argocd.argoproj.io/sync-wave: "0"
    spec:
      project: default
      source:
        repoURL: https://github.com/krzwiatrzyk/showroom.git
        targetRevision: HEAD
        path: argocd-infra-apps-multi-cluster-progressive-rollout-v2/charts/app
        helm:
          releaseName: "{{ .name }}-infra1"
      destination:
        name: "{{ .name }}"
        namespace: "{{ .name }}-infra1"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
