# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: apps
#   namespace: argocd
#   finalizers:
#     - resources-finalizer.argocd.argoproj.io
# spec:
#   project: default
#   source:
#     repoURL: https://github.com/krzwiatrzyk/showroom.git
#     targetRevision: HEAD
#     path: argocd-infra-apps-multi-cluster-progressive-rollout-v2/apps
#     directory:
#       recurse: true
#   destination:
#     name: in-cluster
#     namespace: argocd
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#       - CreateNamespace=true
#       - ServerSideApply=true
