apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  labels:
    argocd.argoproj.io/secret-type: cluster
    type: beta
    windkube.com/infra-ready: "true"
  name: beta1
  namespace: argocd
stringData:
  config: |
    {
      "tlsClientConfig": {
        "insecure": false
      }
    }
  name: beta1
  server: https://kubernetes.default.svc
type: Opaque
